# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSnapkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

  # Pods for TestSnapkit

  target 'TestSnapkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestSnapkitUITests' do
    # Pods for testing
  end

end
